const json=(body,status=200)=>Response.json(body,{status,headers:{'Cache-Control':'no-store'}});
export default {async fetch(request,env){const url=new URL(request.url);if(!url.pathname.startsWith('/api/')){const asset=ASSETS[url.pathname];if(!asset)return new Response('Not found',{status:404});return new Response(request.method==='HEAD'?null:asset.body,{headers:{'Content-Type':asset.type,'Cache-Control':'no-cache','X-Content-Type-Options':'nosniff'}});}
 const user=request.headers.get('oai-authenticated-user-id');if(!user)return json({error:'Sign in to use your private bookmarks.'},401);if(!env.BUCKET)return json({error:'Bookmark storage is unavailable. Please try again later.'},503);
 const hash=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(user));const prefix='bookmarks/'+[...new Uint8Array(hash)].map(b=>b.toString(16).padStart(2,'0')).join('')+'/';
 try{if(url.pathname==='/api/bookmarks'&&request.method==='GET'){let cursor,items=[];do{const page=await env.BUCKET.list({prefix,include:['customMetadata'],limit:1000,...(cursor?{cursor}:{})});items.push(...page.objects.map(o=>({id:o.key.slice(prefix.length),...o.customMetadata})));cursor=page.truncated?page.cursor:null;}while(cursor);return json(items.sort((a,b)=>(b.updated||'').localeCompare(a.updated||'')));}
 const id=url.pathname.match(/^\/api\/bookmarks\/([a-f0-9]{64})$/)?.[1];if(!id)return json({error:'Bookmark not found.'},404);const key=prefix+id;
 if(request.method==='GET'){const object=await env.BUCKET.get(key);return object?new Response(object.body,{headers:{'Content-Type':'application/json','Cache-Control':'no-store'}}):json({error:'This bookmark could not be found.'},404);}
 if(request.method!=='PUT')return json({error:'Method not allowed.'},405);
 if(request.headers.get('Origin')!==url.origin||!(request.headers.get('Content-Type')||'').startsWith('application/json'))return json({error:'Invalid bookmark request.'},403);
 const limit=16*1024*1024;if(Number(request.headers.get('Content-Length'))>limit)return json({error:'This book is too large to bookmark. Try a chapter at a time.'},413);
 const reader=request.body?.getReader();if(!reader)return json({error:'No bookmark supplied.'},400);let size=0,chunks=[];while(true){const {value,done}=await reader.read();if(done)break;size+=value.length;if(size>limit){await reader.cancel();return json({error:'This book is too large to bookmark. Try a chapter at a time.'},413);}chunks.push(value);}let data;try{data=JSON.parse(await new Blob(chunks).text());}catch{return json({error:'Invalid bookmark data.'},400);}
 if(typeof data.title!=='string'||data.title.length>400||!Array.isArray(data.words)||!data.words.length||data.words.length>500000||!Number.isInteger(data.index)||data.index<0||data.index>=data.words.length||!Number.isFinite(data.speed)||data.speed<60||data.speed>800)return json({error:'Invalid bookmark data.'},400);
 for(const word of data.words){if((word.paragraphEnd!==undefined&&typeof word.paragraphEnd!=='boolean')||typeof word.text!=='string'||word.text.length>5000||!Array.isArray(word.parts)||word.parts.length>1000||word.parts.some(p=>typeof p.text!=='string'||typeof p.italic!=='boolean')||word.parts.map(p=>p.text).join('')!==word.text)return json({error:'Invalid text in bookmark.'},400);}
 const saved={title:data.title,words:data.words,index:data.index,speed:data.speed,...(data.paragraphVersion===1?{paragraphVersion:1}:{})};await env.BUCKET.put(key,JSON.stringify(saved),{httpMetadata:{contentType:'application/json'},customMetadata:{title:data.title,index:String(data.index),updated:new Date().toISOString()}});return json({saved:true});
 }catch(error){console.error('Bookmark storage request failed',error?.message);return json({error:'Could not access your bookmarks. Your current text is still available; please try again.'},503);}
}};
